# 婴儿年龄预测项目配置文件

# 数据配置
data:
  raw_data_path: "data/Data_with_age.csv"
  processed_data_path: "data/processed_data.csv"
  test_size: 0.2
  random_state: 42

# 模型配置
model:
  type: "GradientBoostingRegressor"
  params:
    n_estimators: 500
    learning_rate: 0.01
    max_depth: 8
    min_samples_split: 10
    min_samples_leaf: 4
    subsample: 0.8
    max_features: "sqrt"
    random_state: 42

# 特征配置
features:
  categorical: ["cat_id", "cat1", "gender"]
  numerical: ["property_count", "has_special_property", "sum_properties", 
              "day_year", "day_month", 
              "buy_mount_log", "auction_id_last_digits"]

# 输出配置
output:
  model_path: "models/age_prediction_model.pkl"
  predictions_path: "output/predictions.csv"
  metrics_path: "output/metrics.json"